### PR TITLE
Midpoint

### PR DESCRIPTION
**Pull request by irinayiwei**

### CODE REVIEW

**Comment by irinayiwei** [comment]
Pull Request for the midpoint checkpoint. Code scripts are in the create_db folder while slides is in the presentation folder. Any feedback on the progress and next steps will be appreciated!!

**Comment by tangq2** [comment]
Functionality
Is the code doing what it’s meant to?
 Need to add “import boto3” into upload.py

Readability and code quality
•	Is code easy to follow?
The code is clear and easy to follow, but there are many blocks commented out which I think could be deleted if not needed.
•	Can you understand the design decisions that were made? In individual scripts as well as in the code base as a whole?
Yes, the design decisions are easy to understand within individual scripts as well as in the code base as a whole.
•	Are variable and method names meaningful? Is it clear what they are referencing?
The variable and methods names are meaningful, and it is clear what they are referencing.
•	Are methods/functions appropriately sized? Or are there functions that need to be broken apart? Remember best practice is to decouple individual pieces of functionality (to enable testing and facilitate maintenance)
Methods/functions appropriately sized, but some parts of the code are not modular(will discuss about it in the next section)

Overall design
•	Does the code being reviewed make sense in the large context of the application? Is it consistent with the general approach that has so far been taken?
The code overall makes sense and is consistent with the general approach that has so far been taken.
•	Is it modular? Is it extensible ?
Codes in acquire.py and upload.py should be put into callable modules, as well as some of the codes in db.py which aim to create database and database sessions. 
For the acquire.py and upload.py,  a “main” part is needed that allows users to assign the path for downloading data and uploading data.
Also, for the db.py, the script should allow the user to create the database schema locally in sqlite or in RDS based on a configuration.
•	Are there any issues with how the design might impact future development?
Everything looks fine so far.
Testing
•	is the code structured in such a way that it’s easily testable
The code is structured as easily testable and the test part is already included. 
•	Does the PR include tests for the code (where applicable)
Yes

Documentation
•	Are methods and functions properly documented?
The existing methods and functions are properly documented.
•	Thorough docstrings (see http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html (Links to an external site.)Links to an external site. (Links to an external site.)Links to an external site. for best practices for Google formatting)
The remaining codes(as mentioned in the previous session) should be structured into callable functions with docstrings.
•	Are inputs and outputs explained and referenced by the parameter name?
Yes
•	Are there docstrings with descriptions of what functions/methods are doing?
The existing ones, yes.
•	Is there commentary to aid others to understand what is being done throughout the code? (within functions, methods, etc)
Commentary is provided throughout the code.
•	README.md (Links to an external site.)Links to an external site.
o	Does it explain the overall design / approach to the problem?
Need to create a README.md file
Need to add more details as the remaining codes being structured into functions.
o	Does it explain how someone else can get the code, build it, and run it? I.e. are you able to clone their repository and get all functionality so far working without having to ask the developer questions?
I am able to clone their repository and get all functionality so far working without asking, but it could be better if the developer provides more detailed instructions to get the code, build it, and run it.
•	Are commit statements meaningful?
Yes
•	Are changes / additions explained in the PR itself?
Maybe it could be better to provide information about files changed(added) and any other additional explanations to run the code.

**Comment by tangq2** [comment]
Please do:
Make sure package is correctly imported at the beginning of each python file
Add the README.md
Put the remaining scripts into callable functions
Add the argument parse function to the scripts
add some loggings for providing information and debugging purposes

lmk if this is not clear enough

**Comment by irinayiwei** [comment]
Hi thanks for the input!! 
I just made some changes to the code file as well as README, based on your comments. Please take a look and let me know if there is anything else I can improve upon!

**Pull request merged**
